### ISSUE TITLE
Website needs new images

### ISSUE THREAD

**Issue by zmughal** [oh-uhouston-6/oh-uhouston-6.github.io#1]
While the construction gif has a [long and storied history](http://www.movingimage.us/exhibitions/2012/12/04/detail/under-construction/) and comes in [near-infinite varieties](http://www.textfiles.com/underconstruction/), it is perhaps not the best choice for our site.

A tip:

Make sure that the licensing on the image gives you permission to add them. An easy way to make sure if that is to choose Creative Commons-licensed images. You can find great re-usable images on Wikimedia Commons, at http://flickr.com/creativecommons, or by using the advanced search within Google Image Search, just to name a few options.

**Comment by maeghan-dickson** [comment]
I'll do this!

**Comment by zmughal** [comment]
Awesome! Can't wait to make the website much better!

**Comment by maeghan-dickson** [comment]
Added a new picture to the site!

**Comment by zmughal** [comment]
Ah, I thought I got a pull request from you, but I seem to have missed it in all the hectic activity! :-/

I see that you have some commits to merge ("3 commits ahead").
![selection_114](https://cloud.githubusercontent.com/assets/94489/6544242/45609486-c50c-11e4-8dc2-0dad2e2d7ff4.png)

You can create a pull request by clicking the "Pull Requests" tab (in blue) and then clicking the green button labelled "New Pull Request".

![selection_115](https://cloud.githubusercontent.com/assets/94489/6544247/76632fee-c50c-11e4-8e3a-ac15c81d3a51.png)

Then all you need to do is click the green "Create Pull Request" button and confirm that you want to send it and then I'll see it and merge it in.

![selection_116](https://cloud.githubusercontent.com/assets/94489/6544252/a3da3f26-c50c-11e4-8408-58457677d1f8.png)

**Comment by zmughal** [comment]
I went ahead and created the pull request myself. :-)
