### ISSUE TITLE
Javascript bug in the interactive poem

### ISSUE THREAD

**Issue by zmughal** [oh-uhouston-6/oh-uhouston-6.github.io#2]
Expected behavior:  It should go back to the beginning of the poem when you click the last line.

Actual behavior:  It says "undefined" and then gets stuck there.

I think the problem is in poem.js.  Can somebody fix this?

**Comment by asbzan** [comment]
claimed

**Comment by zmughal** [comment]
OK, cool!

**Comment by zmughal** [comment]
Closed by #9. Thank you!
